#!/usr/bin/env bash
#
# https://gist.github.com/mislav/5189704
#
# Like `tmux select-pane`, but if Vim is running in the current pane it sends
# a keystroke to Vim instead.
set -e

cmd="$(tmux display -p '#{pane_current_command}')"

if [ $cmd = "vim" ]; then
  direction="$(echo "${1#-}" | tr 'lLDUR' '\\hjkl')"
  # forward the keystroke to Vim
  tmux send-keys "C-a"
  tmux send-keys "$direction"
else
  tmux select-pane "$@"
fi
